#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jellystat"
name = "Jellystat"
description.en = "A statistics dashboard for Jellyfin servers."
description.fr = "Un tableau de bord de statistiques pour les serveurs Jellyfin."

version = "1.0~ynh1"

maintainers = ["botagas"]

[upstream]
license = "MIT"
website = "https://github.com/CyferShepard/Jellystat"
userdoc = "https://github.com/CyferShepard/Jellystat"
code = "https://github.com/CyferShepard/Jellystat"

[integration]
yunohost = ">= 11.2"
helpers_version = "2.1"
architectures = ["arm64", "amd64"]
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "200M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jellystat"

[resources]
    [resources.sources]
    [resources.sources.main]
    # Specify the repository to clone
    url = "https://github.com/CyferShepard/Jellystat.git"
    sha256 = "ce5387064119399056e3634c9e2b572c3cca5bc7395614627ad5043b5742dd27"
    branch = "main"

    [resources.system_user]
    # Unix system user for the app
    home = "/var/www/jellystat"

    [resources.install_dir]
    # Directory where Jellystat will be installed
    dir = "/var/www/jellystat"

    [resources.permissions]
    # Configure access permissions for SSOwat
    main.url = "/"

    [resources.ports]
    # Reserve the backend port for Jellystat
    main.default = 3000
