#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jellystat"
name = "Jellystat"
description.en = "A statistics dashboard for media servers."

version = "1.1.5~ynh1"

maintainers = ["botagas"]

[upstream]
license = "GPL-3.0-or-later"
code = "https://github.com/CyferShepard/Jellystat"

[integration]
yunohost = ">= 11.2"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "600M"
ram.build = "200M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"
    
    [install.path]
    type = "path"
    default = "/"

    [install.adminuser]
    ask.en = "Which user should be the administrator for the app?"
    type = "user"

    [install.password]
    type = "password"
    optional = true

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://github.com/CyferShepard/Jellystat/archive/refs/tags/1.1.5.tar.gz"
    sha256 = "82e7ab73b13ffe69c9e3fd44906f88a044315e796d61444f3ed11e0be9728e3e"
    branch = "main"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    home = "/var/www/jellystat"

    [resources.install_dir]
    dir = "/var/www/jellystat"
    
    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3000
    
    [resources.apt]
    packages = "npm, postgresql"
