#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jellystat"
name = "Jellystat"
description.en = "A statistics dashboard for Jellyfin servers."

version = "1.1.2~ynh1"

maintainers = ["botagas"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://github.com/CyferShepard/Jellystat"
userdoc = "https://github.com/CyferShepard/Jellystat"
code = "https://github.com/botagas/jellystat_ynh"

[integration]
yunohost = ">= 11.2"
helpers_version = "2.1"
architectures = ["arm64", "amd64"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "200M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"
    
    [install.path]
    type = "path"
    default = "/"

[resources]
    [resources.sources]
    [resources.sources.main]
    # Specify the repository to clone
    url = "https://github.com/CyferShepard/Jellystat/archive/refs/tags/1.1.2.tar.gz"
    sha256 = "53c1ac04910af2df5ebd4b0a46ec1fd6c85c7e84986f4b2a53ff9e1d04fe1a57"
    branch = "main"

    [resources.system_user]
    # Unix system user for the app
    home = "/var/www/jellystat"

    [resources.install_dir]
    # Directory where Jellystat will be installed
    dir = "/var/www/jellystat"
    
    [resources.data_dir]

    [resources.permissions]
    # Configure access permissions for SSOwat
    main.url = "/"

    [resources.ports]
    # Reserve the backend port for Jellystat
    main.default = 3000
    
    [resources.apt]
    # Automatically installs/uninstalls the following packages
    packages = "npm, postgresql"
