#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

BACKUP_CORE_ONLY=0 ynh_backup "$install_dir"
ynh_backup "$data_dir" --not-mandatory

#=================================================
# BACKUP SYSTEM CONFIGURATION
#=================================================

# Backup the NGINX configuration
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

# Backup the systemd service unit
ynh_backup "/etc/systemd/system/$app.service"

#=================================================
# BACKUP THE POSTGRESQL DATABASE
#=================================================
ynh_print_info "Backing up the PostgreSQL database..."

if [ -f "$backup_data/db.sql" ]; then
    # Dump and backup db if present
    ynh_psql_dump_db $postgres_db > "$backup_data/db.sql"
    ynh_backup "$backup_data/db.sql"
else
    ynh_print_warn "No db dump file found in the backup directory. Was the DB not backed up previously?"
    ynh_print_warn "Due to missing db file, the backup will not contain db data..."
    ynh_print_info "Proceeding with backup without db file..."
fi

#=================================================
# END OF SCRIPT
#=================================================
ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
