#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

postgres_db=$(ynh_app_setting_get --app=$app --key=postgres_db)
postgres_user=$(ynh_app_setting_get --app=$app --key=postgres_user)

#=================================================
# STOP AND REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping and removing the systemd service..."

# Remove the dedicated systemd config
if systemctl is-active --quiet "$app"; then
    ynh_systemctl --service="$app" --action="stop"
fi

yunohost service remove "$app"
ynh_config_remove_systemd

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Removing logrotate configuration..."

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression "Removing dependencies..."

# Remove Node.js dependencies (if applicable)
ynh_nodejs_remove

#=================================================
# REMOVE DATABASE
#=================================================
ynh_script_progression "Removing PostgreSQL database..."

# Drop the database and user
ynh_psql_db_shell postgres <<< "DROP DATABASE IF EXISTS $postgres_db;"
ynh_psql_db_shell postgres <<< "DROP ROLE IF EXISTS $postgres_user;"

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

# Remove APT dependencies
ynh_script_progression "Removing APT dependencies..."
ynh_print_warn "This may take a while..."
ynh_apt_remove_dependencies

# Remove the app's configuration and other specific files
install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)
if [ -n "$install_dir" ]; then
    ynh_safe_rm "$install_dir"
else
    echo "Warning: install_dir not found in app settings, using default path."
    ynh_safe_rm "/var/www/jellystat"
fi
ynh_safe_rm "$data_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
