#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping and removing the systemd service..."

# Remove the dedicated systemd config
if ynh_exec_warn_less systemctl is-active --quiet "$app"; then
    ynh_systemctl --service="$app" --action="stop"
fi
ynh_config_remove_systemd

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Removing logrotate configuration..."

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression "Removing dependencies..."

# Remove Node.js dependencies (if applicable)
ynh_nodejs_remove

#=================================================
# REMOVE DATABASE
#=================================================
ynh_script_progression "Removing PostgreSQL database..."

# Drop the database and user
if sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw "$postgres_db"; then
    sudo -u postgres psql -c "DROP DATABASE $postgres_db;"
fi
if sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='$postgres_user'" | grep -q 1; then
    sudo -u postgres psql -c "DROP USER $postgres_user;"
fi

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

# Remove the app's configuration and other specific files
ynh_secure_remove --file="$install_dir"
ynh_secure_remove --file="/var/log/$app"

#=================================================
# REMOVE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Removing the service from YunoHost..."

if ynh_exec_warn_less yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
