#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIRECTORY
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"
ynh_restore "$data_dir"

#=================================================
# RESTORE ENVIRONMENT VARIABLES
#=================================================
ynh_script_progression "Restoring the environment variables file..."

# Set permissions for the .env file, if present
chmod 600 "$install_dir/.env"
chown "$app:$app" "$data_dir"

# Set permissions for the entire install directory
chown -R "$app:$app" "$install_dir"

# Adjust permissions for web-accessible directories
chown -R "$app:www-data" "$install_dir/backend"
chown -R "$app:$app" "$install_dir/backend/backup-data"
chown -R "$app:www-data" "$install_dir/dist"

#=================================================
# RESTORE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Restoring the systemd service..."

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

#=================================================
# RESTORE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Restoring the NGINX configuration..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

#=================================================
# RESTORE DATABASE
#=================================================
ynh_print_info "Restoring the PostgreSQL database..."

# Verify if the database dump exists in the backup directory
if [ -f "$backup_dir/db.sql" ]; then
    # Drop the existing database and user if they exist
    sudo -u postgres psql -c "DROP DATABASE IF EXISTS $postgres_db;"
    sudo -u postgres psql -c "DROP USER IF EXISTS $postgres_user;"

    # Recreate the user
    sudo -u postgres psql -c "CREATE USER $postgres_user WITH PASSWORD '$postgres_password';"
    sudo -u postgres psql -c "ALTER USER $postgres_user CREATEDB;"

    # Recreate the database
    sudo -u postgres psql -c "CREATE DATABASE $postgres_db OWNER $postgres_user;"
    ynh_psql_db_shell $postgres_db <<< "GRANT ALL PRIVILEGES ON DATABASE $postgres_db TO $postgres_user;"

    # Restore the dump into the newly created database
    ynh_psql_db_shell $postgres_db < "$backup_dir/db.sql"
else
    ynh_print_info "No database dump file found in the backup directory..."
fi


#=================================================
# REINSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Reinstalling dependencies..."

ynh_nodejs_install

#=================================================
# ADD SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Adding service in YunoHost..."

yunohost service add $app

#=================================================
# RELOAD AND START SERVICES
#=================================================
ynh_script_progression "Reloading and starting services..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd" --timeout=30
ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
